### ISSUE TITLE
Rename `/bot-twitter` to `/bot`

### ISSUE THREAD

**Issue by benediktkaiser** [sidestream-tech/unified-auctions-ui#128]
Goal:
As we continues to add new features to our bot, we thought it would be appropriate to rename the project from `bot-twitter` to just `bot`.

Steps:

- [x] Rename the folder from
- [x] Rename the project in the `package.json`
- [x] Change the secrets from `auction-ui/bot-twitter` to `auction-ui/bot`
- [x] Updates the ReadMe to display the new name.
- [x] Update the `docker-compose` file
- [x] Update the DockerFile (`/bot-twitter/Dockerfile`)

If there are any other locations we need to change the name, please list them in the issue.

**Comment by valiafetisov** [comment]
- [ ] Drone config (building images, testing)
- [ ] Ingress config (deploying images, applying secrets)

This issue is also about making sure that if no twitter env variables specified, no twitter functionality is activated, without throwing any errors. I think it's already like that, but let's check it once again.

**Comment by benediktkaiser** [comment]
I wanted to ask if we want to also rename all the secret locations with this PR. If yes, I would make a list here and someone with permissions for the production secrets, would then have to be so kind to update them. 😄
