### ISSUE TITLE
Fix `unknown network` error

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#193]
**Context:**
Experienced in production: https://unified-auctions.makerdao.com/collateral
When the wallet is set to a network different than `mainnet`, accessing https://unified-auctions.makerdao.com/collateral leads to two error toasts being displayed (see screenshot below). Additionally the console is flooded with the two repeating errors as well (see screenshot of console log below)
Expectation is that only the network switch modal is shown without throwing these errors.

**Tasks:**
- [ ] Fix problem described above

**Assets:**
Screenshot UI
<img width="597" alt="image" src="https://user-images.githubusercontent.com/36229155/161979490-a0ffa7be-333f-42c0-9729-eeaaca356a20.png">

Screenshot Console Log:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/36229155/161980183-e8d77c10-1455-4613-a52f-3490a15a9cf8.png">

**Comment by fegbert** [comment]
The problem comes from the `getMakerNetwork` getter in the network store. This getter returns `undefined` when the network selected on the page differs from the wallets network.
This getter is, among other places, being used in the 2 functions throwing these errors. These functions then, after some delay, call themselves again which results in this error spam.
Functionality-wise this isn't a problem since the user has to select one of the pop-up options before doing anything on the page which results in fixing this anyways, but if we want to remove these errors we would have to use either the pages networks or the wallets networks getter for fetching these values instead of the `getMakerNetwork` getter.

**Comment by valiafetisov** [comment]
There is should be a better solution involving not initiating auction fetching until we have correct `getMakerNetwork`, but because it also depends on the persist plugin, it gets kind of complicated. One simple solution would be to check `getMakerNetwork` getter before initiating those two calls and skip it otherwise.
