### ISSUE TITLE
Enable MKR management

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#298]
### Goal
The user is able to 
* authorise MKR transactions, 
* give allowance for MKR deposits, 
* check MKR wallet and MKR VAT balance
* deposit and withdraw MKR to and from VAT

### Context
The issue is a subset of the implementation proposal you can find [here](https://github.com/sidestream-tech/unified-auctions-ui/issues/188#issuecomment-1152161469)

Work should be done inside `surplus.ts`

### Tasks
- [ ] Make sure it's possible to call collateral authorization and collateral allowance functions (and also ones that fetch their statuses) with MKR as a parameter
- [ ] Make sure it's possible to call balance and VAT balance with MRK, deposit and withdrawal

### Assets:
Additional information on existing benchmark implementation:

> Currently, we already have functions to interact with `gemLike` contracts. For example [`withdrawCollateralFromVat`](https://github.com/sidestream-tech/unified-auctions-ui/blob/ab0d9eb87f0c35417f06af1918922093c73b0b61/core/src/wallet.ts#L75-L86) which accepts `collateralType` as input. But MKR is not a "collateral type" in our internal sense and can't be added to the [list of collaterals](https://github.com/sidestream-tech/unified-auctions-ui/blob/main/core/src/constants/COLLATERALS.ts). So you either need to modify `withdrawCollateralFromVat` to accept MKR (which would require a lot of refactoring and renaming) or simply copy existing logic into `withdrawMRKFromVat` and modify it to work with MKR. Looking at the code, I actually think second option would make more sense.

**Comment by KirillDogadin-std** [comment]
So it took me quite a while to come closer to understanding the blockchain related allowance logic.

For existing functionality i've mainly taken a look at 

- https://github.com/makerdao/dai.js/blob/76f7ddc842d48e0eebdb4368f84e693509468cac/packages/dai-plugin-scd/src/tokens/Erc20Token.js#L62
- https://github.com/makerdao/auctions-ui/blob/master/hooks/useAllowances.js#L190-L204 (uses the previous repo as dep)

For now i see that apparently one has to use the token of `MKR` directly:

- chainlog does not have the contract to it
- the code in the links above to my understanding also relies on the token itself.

- And as far as i can see the codebase we have is primarily automating the communication with the contracts and not the tokens:
  - does that mean that i should hardcode the process here?
  - or does it meant that i should establish the automation to do the similar thing as the `executeTransaction` currently does, but instead use the token / enable the ERC20 token being used there?

**Comment by valiafetisov** [comment]
Allowance is already done in our codebase, but for DAI instead of MKR:
https://github.com/sidestream-tech/unified-auctions-ui/blob/ee0b64ef23f12cc0dc87267ab2d153547b88e9c4/core/src/authorizations.ts#L77-L87

You can rename this function to `setAllowanceAmountDAI` and create new `setAllowanceAmountMKR`. Note that you not only need to use different token address, but also different `JOIN_` contract. The most useful place to check how it's done would be https://github.com/makerdao/auctions-ui

> chainlog does not have the contract to it

MKR token is actually present in chainlog, but under a different name `MCD_GOV`, you could've reverse search it by first checking MKR address and then searching for its name in chainlog 😉

**Comment by KirillDogadin-std** [comment]
The current state that riddles me with the beharviour of the contracts.

1. The bidding process results into `"Flapper/guy-not-set"`
2. Collecting the auction that has "ready-for-collection" state results into `"Flapper/not-finished"` error

Block number that is used in hardhat is 14078339

The latest code that is running in order to debug and reproduce it: 
  - [branch](https://github.com/sidestream-tech/unified-auctions-ui/tree/interact_surplus)
  - [commit](https://github.com/sidestream-tech/unified-auctions-ui/pull/323/commits/31e7ef064e1cc5bab015b83de1b96638128d3b0b)

Find extended descriptions of the issues (numbered above) below.

1. Bidding
---

To my understanding, the highest bidder is already pre-set in the `kick` method when the auction starts.
So with the successful fetching of the auctions, i don't see how the highest bidder cannot be present in the state of the auction. The reason for that is: in the `kick` function the highest bidder is set and the `kicks` value is incremented. Thus, for every single auction that does not exceed `kicks` index the bidder has to be set. Sadly, trying to call `tend` (bid on the auction) result in the mentioned error code. That would indicate that the auction was either not kicked or was deleted. Neither of these options seem possible because the acution was successfully fetched. 

Reproduce by:

  - start the hardhat on the mentioned above block
  - start the frontend
  - open the console in the browser
  - fetch the auctions by `await this.$nuxt.$store.dispatch('surplus/fetchSurplusAuctions')`
    - 5 auctions, 1 'have-bids' with id `2328`, the others are "ready-for-collection" and the ids are lower.
  - try to bid on the auction 2328 via ` await this.$nuxt.$store.dispatch('surplus/betOnAuction', {auctionIndex: 2328, bet: 16})`
     - fails with `guy-not-set`
  - try to collect via ` await this.$nuxt.$store.dispatch('surplus/collectAuction', 2326)`
    - fails with the `not-finished`
