### ISSUE TITLE
Add `vaults` frontend components

### ISSUE THREAD

**Issue by zoey-kaiser** [sidestream-tech/unified-auctions-ui#433]
### Goal
In #419 we made a mock for the frontend for the new `vaults` page. This issue aims to provide a clean overview of any new components we need as well as any old components we can reuse for this new feature.

I believe we should wait to start making the components until we decided on what the types should look like. I think this will make the development a lot easier as most components require the VaultTypes to function properly. 

<details><summary>Finished Mock</summary>
<p>

![MakerDAO vaults](https://user-images.githubusercontent.com/30908158/187427615-a691aba2-e1ad-4e8a-a847-ca171adba45d.png)

</p>
</details>

### Components Overview

- [ ] VaultsFlow
- [x] Vaults
  - [x] #436
  - [x] #434
- [x] Vault Page
  - [x] #435
  - [x] VaultEventsTable
  - [x] VaultLiquidatedFlow
- [x] VaultLiquidationTransactionFlow
  - [x] #437
  - [x] WalletConnectPanel (already exists)
  - [x] #439
  - [x] #440
- [x] #441 
- [x] #442 

We are currently still writing all the required texts. You can find the current draft [here](https://docs.google.com/document/d/1Ae-xIj5fR53z0VHCK0sObITKOyO2IULk4g1-a3sKAc8/edit?usp=sharing).

**Comment by LukSteib** [comment]
> VaultLiquidationTransactionFlow

Missing the components for the liquidated state here

Other than that LGTM

**Comment by valiafetisov** [comment]
- Why some issues called `Add ... component`, while others don't use word `component`? Suggestion to always use `component` for the frontend issues which are storybook-only, also `Implement` or `Create` will be better than add, since add implies it is already made (eg add a library X) 🙂 
- Why some components are called `Vault...`, while others `Liquidation...`? I suggest to prepend all components with `Liquidation` (not `Liquidated`) instead of the `Vault` or at least `VaultLiquidation`
- `VaultEventsTable` it actually doesn't necessarily need to be a table, since we expect only one type of the event, right? Do you want to change that in the mock as well?

**Comment by zoey-kaiser** [comment]
> * Why some issues called `Add ... component`, while others don't use word `component`? Suggestion to always use `component` for the frontend issues which are storybook-only, also `Implement` or `Create` will be better than add, since add implies it is already made (eg add a library X) 🙂

You are right! I changed all the names of the issues to be more suitable.

> * Why some components are called `Vault...`, while others `Liquidation...`? I suggest to prepend all components with `Liquidation` (not `Liquidated`) instead of the `Vault` or at least `VaultLiquidation`

I decided to use "VaultLiquidation___"

> * `VaultEventsTable` it actually doesn't necessarily need to be a table, since we expect only one type of the event, right? Do you want to change that in the mock as well?

Do we only show the transaction in which the vault became liquidated (`kick` if I am not mistaken)? In that case I agree, that the mocks will need to be adjusted!
