### ISSUE TITLE
Create a simulation for vault liquidation

### ISSUE THREAD

**Issue by valiafetisov** [sidestream-tech/unified-auctions-ui#464]
### Goal

A developer is able to start a simulation which will create a vault and turn it into `liquidatable` state.

### Context

In order to test the new collateral types, but also vault logic, we need to create a reusable simulation steps in order to test related functionality. For this, let's implement a creation of a new vault and make this logic universal across collaterals. Eg:
- Create a vault via `createActiveVault(collateralType)` test logic
  - get tokens of a specific collateral symbol (via overwriting a mapping?)
  - set allowance, collateral auth
  - open vault, deposit collateral
  - ? withdraw all available DAI
- Make vault `liquidatable` by:
  - ? `drip`, ie `collectProtocolFees(collateralType)`
  - or setting OSM price (I guess it's more difficult to make it universal?)

Note:
- This can be implemented as part of the https://github.com/sidestream-tech/unified-auctions-ui/issues/460 or after it, in order to test vault creation

### Tasks

- [x] Come of with the final proposal on how to make it universal across collateral types 
- [x] Implement simulation

**Comment by KirillDogadin-std** [comment]
More specifically:

> get tokens of a specific collateral symbol (via overwriting a mapping?)

via `harhdat_setStorageAt` call

> set allowance, collateral auth

- via `authorizeCollateral`
- via `setAllowanceAmountDAI`

> open vault, deposit collateral

- opening via developing a function that calls the the [cdp manager contract](https://etherscan.io/address/0x5ef30b9986345249bc32d8928b7ee64de9435e39#code) with function `open` and calling `frob` to deposit collateral

> withdraw all available DAI

- seems to be possible via `frob` as well and in the same call

> ? drip, ie collectProtocolFees(collateralType)

if we withdraw all possible dai, then i assume this is the correct approach BUT
  - there's a timeout so that the fees can't be collected every second. we might have to secure this funcitonality by calling `warpTime` on the testnet. 

> or setting OSM price (I guess it's more difficult to make it universal?)

yes, it is. let's avoid it as hard as possible 😓

**Comment by valiafetisov** [comment]
> hre.call('harhdat_setStorageAt', [address, slotAddress, newBalance])

Would [`hardhat_impersonateAccount`](https://hardhat.org/hardhat-network/docs/reference#hardhat_impersonateaccount)  help? It is useful to call methods that require authorization.

Otherwise, I am not sure if you actually need to get tokens first. You might instead modify collateral balance in the VAT directly or write a script that opens a vault, then modifies its collateral size.

> Use dai balance overwrite and try to swap this into the token we need:

Not every token is swappable on Uniswap, as you see, we already have several groups of collaterals that require different exchange callees and it's most likely that this script is helpful when there is no callee yet. So, this option is the least favourable. 

> non-customizable amount of collateral in it

Not sure what you mean. Of course it will be beneficial to set collateral + debt amounts semi-random to be able to test different scenarios.

**Comment by KirillDogadin-std** [comment]
> Would [hardhat_impersonateAccount](https://hardhat.org/hardhat-network/docs/reference#hardhat_impersonateaccount) help? It is useful to call methods that require authorization

Since I don't see the function that just edits the balance of the address at token contract of weth, I cannot say that it helps since impersonation of the token contract does not result into ability to edit some wallet's balance. Correct me if I'm on the wrong line of thinking.

> Otherwise, I am not sure if you actually need to get tokens first. You might instead modify collateral balance in the VAT directly or write a script that opens a vault, then modifies its collateral size.

True, but same with the adjustment of the vat balance. I will double check tomorrow but now I've seen no function that can be called to generate collateral out of thin air

> Not every token is swappable on Uniswap

Let's avoid, true.

> Not sure what you mean. Of course it will be beneficial to set collateral + debt amounts semi-random to be able to test different scenarios.


Some swaps were failing back in the day when we converted DAI to mkr. That was because on the block number there apparently were no open trades that would allow swapping into desired amount

**Comment by valiafetisov** [comment]
> True, but same with the adjustment of the vat balance. I will double check tomorrow but now I've seen no function that can be called to generate collateral out of thin air

Not the same, as there is only one VAT contract, right? If there is a single place, overwriting a mapping would be much more reliable than doing it for different token contracts.

**Comment by KirillDogadin-std** [comment]
> Not the same, as there is only one VAT contract, right? If there is a single place, overwriting a mapping would be much more reliable than doing it for different token contracts.

True, missed this point. Then let's roll with overwrite of this single page

**Comment by KirillDogadin-std** [comment]
relevant article https://github.com/makerdao/developerguides/blob/master/vault/cdp-manager-guide/cdp-manager-guide.md
