### ISSUE TITLE
Display partial liquidation amount

### ISSUE THREAD

**Issue by aomafarag** [sidestream-tech/unified-auctions-ui#486]
### Goal

Display how much of a vault will be liquidated in a partial liquidation 

### Context

For a partial liquidation of a `liquidatable` vault, we only display the difference between each liquidation limit and the vault's debt multiplied by the liquidation penalty ration in the `VaultLiquidationLimitsCheckPanel` (see [screenshot](#screenshot)).

We would like to additionally display the actual amount of the vault's debt that would be liquidated.

### Assets

1. <a name="screenshot">Screenshot</a>
![image](https://user-images.githubusercontent.com/85403429/194057458-545dd513-fcaa-4ccc-bcbd-3315ca6dac41.png)

2. Link to original issue: https://github.com/sidestream-tech/unified-auctions-ui/issues/478
3. Link to the proposal in the PR: https://github.com/sidestream-tech/unified-auctions-ui/pull/485#pullrequestreview-1129815860

### Tasks

- [ ] Add a new row in **bold** below the calculations of the aforementioned differences, with a `Will be liquidated` text on the left and the partial liquidation amount on the right.

**Comment by zoey-kaiser** [comment]
Do we also have to take the minimum liquidation amount into consideration? 

As an example:

Global Limit Max: 5000
Global Limit Current: 4500
Maximum liquidation: 500
Minimum needed liquidation: 1000

I know the state already gets set to `not-liquidatable`, but do we also want to display the reason (being minimum liquidation amount not reached) to avoid confussion?

Otherwise we do not display the reason why it cannot be liquidated.

**Comment by valiafetisov** [comment]
@aomafarag please update description with a link to the original issue + link to the initial proposal in the PR

**Comment by KirillDogadin-std** [comment]
https://github.com/sidestream-tech/unified-auctions-ui/issues/486#issuecomment-1268406271

> @KirillDogadin-std, is this correct?

this is correct
