### ISSUE TITLE
Remove localhost from network modal

### ISSUE THREAD

**Issue by LukSteib** [sidestream-tech/unified-auctions-ui#98]
**Context:**
After last release we show `Localhost:8545` as selection option in network model on UI. This might be misleading for users and we only use it for testing purposes locally. We should remove it from here. 

**Tasks:**
- [x] Briefly check with @valiafetisov whether this is intended
- [ ] Remove the selection from network modal

**Comment by fegbert** [comment]
Since it is used for testing purposes I would suggest hiding it only in the production environment and still showing it elsewhere.
What do you think @valiafetisov? 🙂

**Comment by valiafetisov** [comment]
> This might be misleading for users and we only use it for testing purposes locally. We should remove it from here.

It was actually intended to keep it, since even metamask have this network added by default. But it's then turned out it can't work in production since production is served via `https` and therefore can't connect to `http` endpoint.

In other words, I agree, we should remove it from production as well as staging. 

Implementation-wise: let's use [nuxt builtin `isDev` variable](https://nuxtjs.org/docs/internals-glossary/context/#isdev) to determine the context (accessible via `this.$nuxt?.context?.isDev`). I also recommend to:
- create `getNetworks` function inside `NETWORKS.ts`, which accepts `isDev` (and filters out `localhost` network)
- remove `export default NETWORKS;` from `NETWORKS.ts` and use `getNetworks` everywhere in place of `import NETWORKS`
